env:
  CIRRUS_CLONE_DEPTH: 1
  MSBUILDDISABLENODEREUSE: 1

linux_x64_task:
  container:
     dockerfile: .ci/linux_x64/Dockerfile

  build_script:
    - dotnet build -p:Configuration=Release src/RekoShell.sln
  
  test_script:
    - dotnet test -p:Configuration=Release src/RekoShell.sln